title: Food Image Classifier
description: Classify Food Image Using Deep Learning with fine tuned MobileNetV2
about:


  This is a web app with provides an Image Classifier built on
  top of TensorFlow. The app supports server-side and browser-based
  inference, deployed on the cloud provider Heroku.

  Source code can be found in this repository [deploying-web-app](https://github.com/elliemci/deploying-web-app).


code: https://github.com/elliemci/deploying-web-app.git

image_size: 224
top_k: 5

sampleImages:
  - name: Apple pie
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/10/4/1/FNM_110110-Pies-027_s4x3.jpg.rend.hgtvcom.686.515.suffix/1382539570711.jpeg
  - name: Baby Back Ribs
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/5/14/1/FNM_060114-Smoked-Baby-Back-Ribs-Recipe_s4x3.jpg.rend.hgtvcom.686.515.suffix/1400187281121.jpeg
  - name: Cheese Cake
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/12/9/0/FNK_Cheesecake_s4x3.jpg.rend.hgtvcom.686.515.suffix/1387411272847.jpeg
  - name: Chicken Curry
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/12/03/wu2403__chicken-curry-in-a-hurry_s4x3.jpg.rend.hgtvcom.686.515.suffix/1575405655829.jpeg
  - name: Chicken Wings
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/2/19/1/FN_Air-Fryer-Chicken-Wings-H_s4x3.jpg.rend.hgtvcom.686.515.suffix/1550611553388.jpeg
  - name: Chocolate Cake
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/3/18/0/FNK_German-Chocolate-Cake-Slice_s4x3.jpg.rend.hgtvcom.686.515.suffix/1396383143215.jpeg
  - name: Scallops
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/4/1/2/LS-Library_Scallop-Scampi_s4x3.jpg.rend.hgtvcom.686.515.suffix/1522678867103.jpeg
  - name: Steak
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/4/26/0/FNM_060110-Bobby-Grilling-013_s4x3.jpg.rend.hgtvcom.686.515.suffix/1382539247827.jpeg
  - name: Waffles
    url: https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/9/28/0/FNK_Classic-Crispy-Waffles_s4x3.jpg.rend.hgtvcom.966.725.suffix/1383787355520.jpeg
  - name: Granny Smith Apple (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/d/d7/Granny_smith_and_cross_section.jpg
  - name: Salad (not in training data)
    url : https://upload.wikimedia.org/wikipedia/commons/9/94/Salad_platter.jpg
  - name: Labrador retriever (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg
  - name: iPhone (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/3/3b/IPhone_5s_top.jpg
