title: Food Image Classifier
description: Classify Food Image Using Deep Learning with fine tuned MobileNetV2
about:


  This is a web app with provides an Image Classifier built on
  top of TensorFlow. The app supports server-side and browser-based
  inference, deployed on the cloud provider Heroku.

  Source code can be found in this repository [deploying-web-app](https://github.com/elliemci/deploying-web-app).


code: https://github.com/elliemci/deploying-web-app.git

image_size: 224
top_k: 3

sampleImages:
  - name: Cheese Cake
    url: https://upload.wikimedia.org/wikipedia/commons/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg
  - name: Chicken Quesadilla
    url: https://upload.wikimedia.org/wikipedia/commons/7/75/Quesadilla_2.jpg
  - name: Chicken Wings
    url: https://upload.wikimedia.org/wikipedia/commons/d/dd/Buffalo_-_Wings_at_Airport_Anchor_Bar.jpg
  - name: Chocolate Cake
    url: https://upload.wikimedia.org/wikipedia/commons/6/6a/ChocolateTruffleCakeIdeal01.JPG
  - name: Granny Smith Apple (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/d/d7/Granny_smith_and_cross_section.jpg
  - name: Salad (not in training data)
    url : https://upload.wikimedia.org/wikipedia/commons/9/94/Salad_platter.jpg
  - name: Labrador retriever (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/3/34/Labrador_on_Quantock_%282175262184%29.jpg
  - name: iPhone (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/3/3b/IPhone_5s_top.jpg
