title: Food Image Classifier
description: Classify Food Image Using Deep Learning with fine tuned MobileNetV2
about:


  This is a web app with provides an Image Classifier built on
  top of TensorFlow. The app supports server-side and browser-based
  inference, deployed on the cloud provider Heroku.

  Source code can be found in this repository [deploying-web-app](https://github.com/elliemci/deploying-web-app).


code: https://github.com/elliemci/deploying-web-app.git

image_size: 224
top_k: 3

sampleImages:
  - name: Cheese Cake
    url: https://upload.wikimedia.org/wikipedia/commons/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg
  - name: Chicken Wings
    url: https://upload.wikimedia.org/wikipedia/commons/d/dd/Buffalo_-_Wings_at_Airport_Anchor_Bar.jpg
  - name: Chocolate Cake
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Chocolate_fudge_cake.jpg/220px-Chocolate_fudge_cake.jpg
  - name: Doughnut
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Christmas_doughnut_%2815456531431%29.jpg/220px-Christmas_doughnut_%2815456531431%29.jpg
  - name: French fries
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Fries_2.jpg/1280px-Fries_2.jpg
  - name: Ice cream
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg/220px-Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg
  - name: Miso soup
    url: https://upload.wikimedia.org/wikipedia/commons/a/a1/Tofu_in_miso_soup_by_cathykid_in_Taipei.jpg
  - name: Pizza
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg/1280px-Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg
  - name: Stake
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Steak_with_shitaki_mushrooms.jpg/300px-Steak_with_shitaki_mushrooms.jpg
  - name: Sushi
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/220px-Sushi_platter.jpg
  - name: Waffles
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Waffles_with_Strawberries.jpg/220px-Waffles_with_Strawberries.jpg
